graph LR
    %% スタイルの定義
    %% classDef hardware fill:#e1f5fe,stroke:#01579b,stroke-width:2px;
    %% classDef server fill:#e8f5e9,stroke:#2e7d32,stroke-width:2px;
    %% classDef db fill:#fff9c4,stroke:#fbc02d,stroke-width:2px;

    subgraph Sensors [センサー群]
        DHT[温湿度センサー]
        Photo[光センサー]
        MHZ[CO2センサー]
    end

    subgraph Output_Status[液晶]
        OLED[OLED]
    end

    subgraph Arduino_Unit [Arduino側]
        Arduino[Arduino Uno R4]
    end

    subgraph Linux_Server [Linux Server]
        direction TB
        Receiver[<b>データ受け渡し</b><br>PHP]
        Database[(<b>データベース</b><br>PostgreSQL)]
        WebApp[<b>Webアプリ/表示</b><br>Nginx + HTML/PHP]
    end

    User((教師者/管理者))

    %% 接続関係
    DHT -->|Digital| Arduino
    Photo -->|Analog| Arduino
    MHZ -->|Analog| Arduino
    

    Arduino ==>|HTTP| Receiver
    Receiver -->|PHP| Database
    Arduino -->|I2C| OLED
    
    User -->|アクセス| WebApp
    WebApp -->|要求| Database
    Database -->|応答| WebApp

    %% クラス適用
    class DHT,Photo,MHZ,Arduino hardware;
    class Receiver,WebApp server;
    class Database db;